### ISSUE TITLE
posti_tracking does not work

### ISSUE THREAD

**Issue by Trampasi** [jesmak/posti_tracking#2]
Hey

Thanks for the great HA integration :)
After the last HA updates, posti_tracking integration has not worked anymore. I reinstalled the latest version of the integration V1.01 few times, but the integration still doesn't work.
Here is the error from the log:

ERROR (MainThread) [homeassistant.components.sensor] posti_tracking: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 521, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in async_device_update
    await Coro
  File "/config/custom_components/posti_tracking/sensor.py", line 141, in async_update
    latest_event = shipment['events'][-1]
IndexError: list index out of range.

thank you

**Comment by quenthal** [comment]
I'm having same issue. Is this common problem? Did you @Trampasi got this fixed?

posti_tracking: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 707, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1268, in async_device_update
    await self.async_update()
  File "/config/custom_components/posti_tracking/sensor.py", line 141, in async_update
    latest_event = shipment['events'][-1]
                   ~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range

**Comment by jesmak** [comment]
This issue was fixed with release v1.0.2.
